### PR TITLE
Adding linting with eslint

### PR DESCRIPTION
**Pull request by lfilho**

### CODE REVIEW

**Comment by joshwnj** [comment]
:+1:

**Comment by joshwnj** [comment]
@lfilho can you please rebase to resolve conflicts?

**Comment by joshwnj** [comment]
Can you also please add `eslint` to package.json and add a `lint` script, so we can do `npm run lint` without relying on `eslint` being globally available?

**Comment by lfilho** [comment]
Will do!

**Comment by lfilho** [comment]
Done! There some 5 erros when linting, but they involve changing the code a bit, so I left them in there for now. Only did the very basics that wouldn't introduce significant changes to the code...

**Comment by joshwnj** [comment]
Cool! One final thing before we merge: can you please move the new deps to `package.devDependencies`?

**Comment by lfilho** [comment]
Doh! Done!

**Comment by joshwnj** [comment]
thanks!

**Pull request merged**
